/** @jsx React.DOM */
var React = require('react');
var RecommendForm = require('./RecommendForm.jsx')
var SongFooter = require('./SongFooter.jsx');
var SongMenu = require('./SongMenu.jsx');
var SongSearchColumn = require('./SongSearchColumn.jsx');
var SongBot = require('./SongBot.jsx');
var SongList = require('./SongList.jsx');

var RecommendBox = React.createClass({
    getInitialState: function() {
        return {data: []};
    },
    handleCommentSubmit: function(song) {
        var songs = this.state.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        $.ajax({
            url: this.props.url,
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            dataType: 'json',
            type: 'POST',
            data: JSON.stringify(song),
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                this.setState({data: song});
                console.error(this.props.url, status, err.toString());
            }.bind(this)
        });
    },
    render: function() {
        return (
            <div className="commentBox">
                <SongMenu/>
                <div id="content_song">
                    <SongSearchColumn/>
                    <div id="content_column_two">
                        <div class="form-style-3">
                            <RecommendForm onCommentSubmit={this.handleCommentSubmit}/>
                        </div>
                        <SongList data={this.state.data} />
                    </div>
                    <SongBot/>
                    <div class="cleaner">&nbsp;</div>
                </div>
            </div>
        );
    }
});
module.exports = RecommendBox